### ISSUE TITLE
add web demo/model to Huggingface

### ISSUE THREAD

**Issue by AK391** [salesforce/CodeGen#2]
Hi, would you be interested in adding CodeGen to Hugging Face? The Hub offers free hosting, and it would make your work more accessible and visible to the rest of the ML community. There is already a Salesforce organization on Huggingface: https://huggingface.co/Salesforce to add models/datasets/spaces(web demos) to.

Example from other organizations:
Keras: https://huggingface.co/keras-io
Microsoft: https://huggingface.co/microsoft
Facebook: https://huggingface.co/facebook

Example spaces with repos:
github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/salesforce/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

and here are guides for adding spaces/models/datasets to your org

How to add a Space: https://huggingface.co/blog/gradio-spaces
how to add models: https://huggingface.co/docs/hub/adding-a-model
uploading a dataset: https://huggingface.co/docs/datasets/upload_dataset.html

Please let us know if you would be interested and if you have any questions, we can also help with the technical implementation.

**Comment by enijkamp** [comment]
Yes, definitely, thank you for the pointer. We are working on a HF integration with Leandro et al. as we speak

**Comment by sallumandya1995** [comment]
im interested in integration to HF

**Comment by redthing1** [comment]
I have messed around with this and got it working, here are my unnoficial release:
@sallumandya1995 @AK391 

https://huggingface.co/xhyi/CodeGen-350M-Multi
https://huggingface.co/xhyi/CodeGen-2B-Multi

**Comment by smith-co** [comment]
@redthing1 can you add some example how to run for inference?

**Comment by nashid** [comment]
@enijkamp Any update with the HF integration? 🙏

**Comment by rooa** [comment]
@nashid It's ongoing; should be ready soon!: https://github.com/huggingface/transformers/pull/17443

**Comment by rooa** [comment]
@nashid The pull request is merged. You could give it a try after installing `transformers` from the repo directly.

**Comment by nashid** [comment]
@rooa Cant find codegen [here](https://huggingface.co/docs/transformers/index). Missing something?

**Comment by rooa** [comment]
You can find in the main branch [here](https://huggingface.co/docs/transformers/main/en/index). It would take some time until this integration is included in a new release.

**Comment by nashid** [comment]
@enijkamp tried the URL. I am getting this error "500 Sorry, there is an error on our side.'

**Comment by enijkamp** [comment]
@nashid The gradio serving may have issues handling the load.

Here a colab demo on GPU:
https://colab.research.google.com/drive/11YU00W-JLNXn-3YckJGOSxFf_TQfCXYr#scrollTo=UUq-rqNGOa0L
