### ISSUE TITLE
How to run Codegen locally?

### ISSUE THREAD

**Issue by smith-co** [salesforce/CodeGen#21]
Can I try out Codegen locally for code generation as an alternative to CoPilot?

Is there a way to try the model locally and query the model with prompts?

**Comment by rooa** [comment]
@smith-co You could clone this repository and follow the instruction on the README to try the model locally.

**Comment by smith-co** [comment]
I am trying to follow the steps in Mac m1. I am getting the following errors during setup:

```
> pip3 install -r requirements.txt

Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.9.0+cu111 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0)
ERROR: No matching distribution found for torch==1.9.0+cu111
```

Do I need to have GPU to run it?

**Comment by rooa** [comment]
Hi @smith-co , having a GPU is not the requirement, but the specified version in the `requirements.txt` assumes a GPU. Sorry for the confusion!

I don't have an M1 Mac to test right now, but you might instead want to try the model via `transformers` repo, now that the integration is finished. You can do so by installing the library from the main branch (not available in a release yet).

**Comment by LowinLi** [comment]
Suggest my [repo](https://github.com/LowinLi/fastgpt/tree/main/example/codegen) for run Codegen locally.
I have quantized CodeGen model by onnx. It can run faster in CPU devices in onnxruntime. I have built a web server by gunicorn for web API. The server can deploy through the docker container and serve for [inlineCompletions vscode plugin](https://github.com/LowinLi/code-clippy-vscode).

**Comment by glicerico** [comment]
@rooa how to use the `device=cpu` option if using transformers?
