### ISSUE TITLE
BigPython Availability

### ISSUE THREAD

**Issue by gugarosa** [salesforce/CodeGen#22]
Hello! I hope everything is going well with you.

First, I would like to appreciate in publishing open-sourced pre-trained models and the quality of the paper, they are amazing!

Are there any plans in releasing or publishing a script to create the BigPython dataset? I have looked around and could not find any reference on such a dataset.

Thank you and best regards,
Gustavo.

**Comment by enijkamp** [comment]
Hi Gustavo,

Thank you for the interest!

We don't have any plans to release the pre-processing scripts or training data-sets.
