### ISSUE TITLE
ValueError: Tokenizer class CodeGenTokenizer does not exist or is not currently imported.

### ISSUE THREAD

**Issue by robotPin** [salesforce/CodeGen#23]
[https://huggingface.co/Salesforce/codegen-2B-mono](url)
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("Salesforce/codegen-2B-mono")
model = AutoModelForCausalLM.from_pretrained("Salesforce/codegen-2B-mono")

text = "def hello_world():"
input_ids = tokenizer(text, return_tensors="pt").input_ids

generated_ids = model.generate(input_ids, max_length=128)
print(tokenizer.decode(generated_ids[0], skip_special_tokens=True))

**ValueError: Tokenizer class CodeGenTokenizer does not exist or is not currently imported.**

**Comment by rooa** [comment]
@robotPin Could you let me know the transfomers version? Our model is not included in a release yet, so you'd have to install from the repo, i.e.
```
pip install git+https://github.com/huggingface/transfomers.git
```

**Comment by robotPin** [comment]
Version: 4.20.1

Upgrade to the Version: 4.21.0.dev0 problem solving


thank you @[rooa](https://github.com/rooa)

**Comment by iateadonut** [comment]
> 



> pip install git+https://github.com/huggingface/transfomers.git

that repo doesn't exist.

**Comment by robotPin** [comment]
> > 
> 
> > pip install git+https://github.com/huggingface/transfomers.git
> 
> that repo doesn't exist.

pip install git+https://github.com/huggingface/transformers.git 
transfomers  less than r
transformers
