### ISSUE TITLE
add google colab link

### ISSUE THREAD

**Issue by Penguin-jpg** [salesforce/CodeGen#3]
Hello! I modified a colab notebook. It can be used to interact with CodeGen!
Here is the link: https://colab.research.google.com/drive/1fQI8OgzMAR0bquCrvhlAtXSw6iMFbVgI
Original notebook: https://colab.research.google.com/drive/1Bi2TnSUp2vNiSUhamsNuC4HqkZ2J4WwZ?usp=sharing

**Comment by enijkamp** [comment]
Wonderful work @Penguin-jpg, thank you. Adding it to the readme.

**Comment by enijkamp** [comment]
Added, thank you!

**Comment by Penguin-jpg** [comment]
> 

You are welcome! CodeGen is amazing^^.
