### ISSUE TITLE
MTPB benchmark

### ISSUE THREAD

**Issue by giulio98** [salesforce/CodeGen#33]
Hello,
I saw that you released the MTPB benchmark recently, do you plan to release also the script to evaluate CodeGen in multi-turn or single-turn using the MTPB dataset?

Thank you in advance.

**Comment by yueatsprograms** [comment]
I'm also looking for a script of this kind. Thank you!

**Comment by enijkamp** [comment]
Thank you for the interest! We will add the MTBP execution scripts soon.

**Comment by enijkamp** [comment]
@giulio98 @yueatsprograms The MTBP sampling and execution scripts can be found here:

https://github.com/salesforce/CodeGen/tree/main/benchmark

**Comment by giulio98** [comment]
Thanks for uploading, how to run the script in single-turn evaluation?
