### ISSUE TITLE
How do I train this on custom data?

### ISSUE THREAD

**Issue by hg0428** [salesforce/CodeGen#36]
I am completely new to AI, I would like to know how I can train it to recognize a new language.
I have no idea what to do. I can find no docs online about this. I have attempted to train it using the Trainer from transformers, but I keep coming up with errors. Can I have a code example for this?

**Comment by enijkamp** [comment]
You can find a minimal example of fine-tuning the models with DeepSpeed here:

https://github.com/salesforce/jaxformer#a100-fine-tune

**Comment by hg0428** [comment]
> You can find a minimal example of fine-tuning the models with DeepSpeed here:
> 
> https://github.com/salesforce/jaxformer#a100-fine-tune

How can I do it with my own custom data? I have a dict of expected inputs to expected outputs.

**Comment by hg0428** [comment]
> You can find a minimal example of fine-tuning the models with DeepSpeed here:
> 
> https://github.com/salesforce/jaxformer#a100-fine-tune

@enijkamp I need help here, I can't find any online resources.
