### ISSUE TITLE
Problems With HumanEval

### ISSUE THREAD

**Issue by MT010104** [salesforce/CodeGen#39]
Thanks for the work. CogeGen has achieved relatively good results on HumanEval, but I wanna know how the model is finetuned. Because it only has 164 problems, can you provide parameters for finetuning?

**Comment by rooa** [comment]
CodeGen is only pre-trained on the datasets mentioned in the paper, then evaluated on HumanEval in a zero-shot manner. There is no fine-tuning involved.
