### ISSUE TITLE
How to predict using the model ?

### ISSUE THREAD

**Issue by SubhajitC-Hexaware** [salesforce/CodeGen#42]
I am running the code in kaggle but once the blocks completed running nothing's happening am I not supposed to predict PL by giving NL or how do I go about it ?

**Comment by enijkamp** [comment]
@SubhajitC-Hexaware The notebook has been revised. Let me know if it works for you:

https://colab.research.google.com/drive/11YU00W-JLNXn-3YckJGOSxFf_TQfCXYr?usp=sharing
