### ISSUE TITLE
Use in Visual Studio Code.

### ISSUE THREAD

**Issue by smart2pet** [salesforce/CodeGen#47]
Does it possible to use it in Visual Studio Code?

**Comment by paolorechia** [comment]
It’s possible, but someone has to build the extension (I haven’t seen one yet).

I’m playing with this model locally too, I might give it a go at building a VSCode extension for it.

(I packed the 350M model into a rest API Docker that runs on CPU for this purpose: https://github.com/paolorechia/open-code-gen-api)

**Comment by little51** [comment]
Base on salesforce/CodeGen,I made a Visual Studio Code Extension: 
https://github.com/git-cloner/codegeeker
backend:
https://github.com/git-cloner/codegen

**Comment by epinnock** [comment]
Hi All,
Be sure to take a look at this repo as well : https://github.com/fauxpilot/fauxpilot it also has a simple vscode extension as well, also there is this project https://github.com/THUDM/CodeGeeX

**Comment by smart2pet** [comment]
Thanks.

**Comment by Fusseldieb** [comment]
Such a good model, but lacks the extension to use it properly. Bummer... 

I hope someone actually makes a good extension for it, comparable to the Copilot one.

**Comment by paolorechia** [comment]
@Fusseldieb 
I’ve never tried it, but in theory you can configure GitHub copilot to talk to fauxpilot server: https://github.com/fauxpilot/fauxpilot/blob/main/documentation/client.md#copilot-plugin

That’s probably the best way to use this model on VSCode today

**Comment by james-ef** [comment]
Just to close the loop for anyone else searching - official Visual Studio Code plugin https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-einstein-gpt
