### ISSUE TITLE
[Bug] Please update your huggingface code

### ISSUE THREAD

**Issue by PoodleWang** [salesforce/CodeGen#48]
huggingface: https://github.com/huggingface/transformers/blob/main/src/transformers/models/codegen/modeling_codegen.py#L101

Your request: https://github.com/salesforce/CodeGen/commit/c1c49ab9c5933850adea41575a2d2634ee7b683e

You already update your model. However, you don't update your hugginfgace code. Please update it and also update your checkpoint if you can.

**Comment by rooa** [comment]
Hi, is this issue related to you: https://github.com/huggingface/transformers/issues/20397? 
The highlighted piece of code is common with GPT-J. Could you prepare minimal code to reproduce this? Thanks!
