### ISSUE TITLE
Is there a way to prevent reloading parameters?

### ISSUE THREAD

**Issue by Penguin-jpg** [salesforce/CodeGen#5]
Hello! I have been using CodeGen to generate lately. But I found that I spent most of the time on loading parameters.
I tried to separate out the create_model part to prevent it from reloading but cuda out of memory occurred.
So I want to know is there a way to prevent reloading parameters? 
Thanks!

**Comment by enijkamp** [comment]
https://colab.research.google.com/drive/12LF5GlUmvchpx7niMiUD737q7xvoTzPr?usp=sharing

If you execute the last cell, it appears the amount of allocated cuda memory remains constant.

Does this help?

**Comment by enijkamp** [comment]
Glad it helps. Perhaps, you could update your shared notebook, so that users can easily try multiple samples?

**Comment by Penguin-jpg** [comment]
> Glad it helps. Perhaps, you could update your shared notebook, so that users can easily try multiple samples?

Sure. But I found that changing model causes a TypeError

I changed from 350M-mono to 2B-mono:
![image](https://user-images.githubusercontent.com/69071861/161941913-06e43af7-fba7-4d5c-ad50-1febac3bb824.png)

**Comment by rooa** [comment]
Thanks for reporting this! I was able to reproduce the issue. This was because reloading of the tokenizer caused hiccups with `max_model_input_sizes` when tokenizing `truncation=True`. I have modified the tokenizer call to explicitly use the specified `max_length` in this commit: 22b81d6f2a777daabfca17ac701363e012f21a02. 

Could you reset the runtime and try again?

**Comment by enijkamp** [comment]
There was a minor typo in the 350M-multi url. Here simplified code. Could you test and revise your shared notebook? Thank you.

https://colab.research.google.com/drive/12LF5GlUmvchpx7niMiUD737q7xvoTzPr?usp=sharing

**Comment by Penguin-jpg** [comment]
@enijkamp @rooa Problems solved. Thanks for help!! The notebook is updated.
Here is the link: https://colab.research.google.com/drive/1fQI8OgzMAR0bquCrvhlAtXSw6iMFbVgI?usp=sharing

**Comment by enijkamp** [comment]
Great, thanks!
