### ISSUE TITLE
Does codegen-16B-mono support "load_in_8bit" in huggingface?

### ISSUE THREAD

**Issue by Leolty** [salesforce/CodeGen#58]
As titled. I feel that I cannot load it with int8 on a single GPU (24G)

**Comment by Leolty** [comment]
nvm, I have solved this. It works perfectly fine now. Thanks

**Comment by peppa-nwpu** [comment]
Do you know how to fine-tune the codegen model with your own code dataset?

**Comment by Leolty** [comment]
@peppa-nwpu Hi, maybe you can refer this [`finetune.py`](https://github.com/Leolty/repobench/blob/main/finetune.py), this is what I did to finetune. You can customize the [`CodeGenDataset`](https://github.com/Leolty/repobench/blob/548cfc36e8adf17bbb5d7b8efeeec3fde1992f54/finetune.py#L127) for your own code data.
